name: metadatawriter
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  file_picker: ^6.1.1
  flutter:
    sdk: flutter
  http: ^1.2.0
  metadata_god: ^0.5.2+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
